# Generated by Django 3.2.12 on 2022-11-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221126_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='restaurant',
        ),
    ]
