# Generated by Django 3.2.12 on 2022-11-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_foodcategory_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='food',
            name='active_status',
        ),
    ]
