# Generated by Django 3.2.12 on 2022-11-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
