# Generated by Django 3.2.12 on 2022-11-28 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_food_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='food_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='myapp.foodcategory'),
        ),
    ]
