# Generated by Django 3.2.12 on 2022-11-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart_food_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='food_cat',
            new_name='category',
        ),
    ]
