# Generated by Django 3.2.12 on 2022-11-28 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_food_cat_cart_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res', to='myapp.restaurant'),
        ),
    ]
