# Generated by Django 3.2.12 on 2022-11-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_cart_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='completed',
            new_name='buynow',
        ),
    ]
