# Generated by Django 3.2.12 on 2022-11-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20221129_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='buynow',
            field=models.BooleanField(default=True),
        ),
    ]
